// Package compact implements cache-preserving conversation compaction.
// The Hermes pattern: preserve Head (initial messages — kept verbatim so
// the Anthropic prompt cache prefix survives) and Tail (most recent
// messages — needed for context continuity). Replace the Middle with a
// single structured markdown summary generated by an LLM.
package compact

import (
	"context"
	"fmt"
	"strings"

	"github.com/jedutools/gil/core/provider"
)

// Result describes what one compaction did.
type Result struct {
	OriginalCount   int    // # messages before
	CompactedCount  int    // # messages after
	SavedTokens     int64  // estimated saved tokens
	SummaryMarkdown string // the synthetic message body inserted between head and tail
	Skipped         bool   // true when Compact decided not to compact (middle too small)
}

// Compactor implements the Hermes cache-preserving compaction pattern.
type Compactor struct {
	Provider  provider.Provider
	Model     string
	HeadKeep  int // first N messages kept verbatim; default 2
	TailKeep  int // last N messages kept verbatim; default 6
	MinMiddle int // skip if middle has fewer than this many messages; default 8
}

// Compact returns a NEW message slice. The original is not mutated (deep-copy semantics).
// Layout: [head...] + [synthetic-summary-message] + [tail...].
// When the middle is smaller than MinMiddle, returns the original messages
// (in a fresh slice) and Result{Skipped: true, OriginalCount==CompactedCount}.
func (c *Compactor) Compact(ctx context.Context, msgs []provider.Message) ([]provider.Message, Result, error) {
	headKeep := c.HeadKeep
	if headKeep <= 0 {
		headKeep = 2
	}
	tailKeep := c.TailKeep
	if tailKeep <= 0 {
		tailKeep = 6
	}
	minMiddle := c.MinMiddle
	if minMiddle <= 0 {
		minMiddle = 8
	}

	// Always return a NEW slice — never mutate original.
	if len(msgs)-headKeep-tailKeep < minMiddle {
		// Skip path: deep-copy and return as-is.
		out := make([]provider.Message, len(msgs))
		for i := range msgs {
			out[i] = cloneMessage(msgs[i])
		}
		return out, Result{
			OriginalCount:  len(msgs),
			CompactedCount: len(msgs),
			Skipped:        true,
		}, nil
	}

	head := msgs[:headKeep]
	middle := msgs[headKeep : len(msgs)-tailKeep]
	tail := msgs[len(msgs)-tailKeep:]

	// Build summary prompt — inline for T1; T2 will extract to template.go.
	prompt := buildSummaryPrompt(middle)
	resp, err := c.Provider.Complete(ctx, provider.Request{
		Model: c.Model,
		Messages: []provider.Message{{
			Role:    provider.RoleUser,
			Content: prompt,
		}},
		MaxTokens: 2048,
	})
	if err != nil {
		return nil, Result{}, fmt.Errorf("compact summary: %w", err)
	}

	// Build output: cloned head + summary message + cloned tail.
	out := make([]provider.Message, 0, headKeep+1+tailKeep)
	for _, m := range head {
		out = append(out, cloneMessage(m))
	}
	out = append(out, provider.Message{
		Role:    provider.RoleUser,
		Content: resp.Text,
	})
	for _, m := range tail {
		out = append(out, cloneMessage(m))
	}

	saved := estimateTokens(middle) - estimateTokens([]provider.Message{{Content: resp.Text}})
	if saved < 0 {
		saved = 0
	}
	return out, Result{
		OriginalCount:   len(msgs),
		CompactedCount:  len(out),
		SavedTokens:     saved,
		SummaryMarkdown: resp.Text,
	}, nil
}

// cloneMessage performs a deep copy: ToolCalls and ToolResults slices are duplicated.
func cloneMessage(m provider.Message) provider.Message {
	out := provider.Message{
		Role:    m.Role,
		Content: m.Content,
	}
	if len(m.ToolCalls) > 0 {
		out.ToolCalls = make([]provider.ToolCall, len(m.ToolCalls))
		copy(out.ToolCalls, m.ToolCalls)
		// Input is json.RawMessage (a byte slice); deep-copy each entry.
		for i := range out.ToolCalls {
			if len(out.ToolCalls[i].Input) > 0 {
				cp := make([]byte, len(out.ToolCalls[i].Input))
				copy(cp, out.ToolCalls[i].Input)
				out.ToolCalls[i].Input = cp
			}
		}
	}
	if len(m.ToolResults) > 0 {
		out.ToolResults = make([]provider.ToolResult, len(m.ToolResults))
		copy(out.ToolResults, m.ToolResults)
	}
	return out
}

// estimateTokens: 1 token ≈ 4 chars across all content fields.
func estimateTokens(msgs []provider.Message) int64 {
	total := int64(0)
	for _, m := range msgs {
		total += int64(len(m.Content)) / 4
		for _, tc := range m.ToolCalls {
			total += int64(len(tc.Input)) / 4
		}
		for _, tr := range m.ToolResults {
			total += int64(len(tr.Content)) / 4
		}
	}
	return total
}

// buildSummaryPrompt builds a simple inline prompt. T2 replaces this with template.go.
func buildSummaryPrompt(middle []provider.Message) string {
	var sb strings.Builder
	sb.WriteString("Summarize the following conversation segment as concise markdown.\n\nSegment:\n")
	for _, m := range middle {
		sb.WriteString("[")
		sb.WriteString(string(m.Role))
		sb.WriteString("] ")
		sb.WriteString(m.Content)
		sb.WriteString("\n")
	}
	return sb.String()
}
