// client.go — Modal CLI client helpers (manifest generation, app naming).
//
// The Modal SDK is Python-only (modal.Sandbox / modal.App). gil drives Modal
// by shelling out to the `modal` CLI against an ephemeral Python manifest
// that we generate per-session. This file contains the manifest template and
// the small helpers that own the path layout, with no dependency on cloud/.
//
// References:
//   - https://modal.com/docs/guide/sandbox    (Sandbox concept)
//   - https://modal.com/docs/reference/cli/run (modal run --<arg> <value>)
//   - https://modal.com/docs/reference/cli/app (modal app stop <name>)
package modal

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// AppName returns the deterministic Modal app name for a gil session.
// Modal app names must be DNS-label-ish (lowercase, alnum, dashes). The
// "gil-" prefix lets `modal app list | grep gil-` match every session.
func AppName(sessionID string) string {
	// Simple sanitizer: lowercase, replace anything non-[a-z0-9-] with '-'.
	// Modal accepts up to ~64 chars; a UUID-ish sessionID fits comfortably.
	out := make([]byte, 0, len(sessionID)+4)
	out = append(out, []byte("gil-")...)
	for _, r := range strings.ToLower(sessionID) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-':
			out = append(out, byte(r))
		default:
			out = append(out, '-')
		}
	}
	return string(out)
}

// ManifestPath returns the path of the ephemeral Python manifest for a
// session. The default base dir is /tmp; tests override via os.TempDir().
func ManifestPath(sessionID string) string {
	return filepath.Join(os.TempDir(), "gil-modal-"+sessionID+".py")
}

// ManifestSpec is the input to RenderManifest. It captures every value
// the Python template needs.
type ManifestSpec struct {
	AppName      string   // gil-<sessionID>
	Image        string   // pip-installable hint, e.g. "python:3.12-slim" — passed as comment only.
	PipPackages  []string // optional pip packages baked into the image
	WorkspaceDir string   // local dir to mount as /workspace in the sandbox
}

// RenderManifest produces the Python source that defines the gil Modal app.
// The exec_in_sandbox function is the entrypoint invoked by `modal run
// <manifest>::exec_in_sandbox --cmd <cmd> --args <json>`.
//
// We deliberately keep this template minimal and string-templated (not
// text/template) so it is trivially auditable in a code review.
func RenderManifest(spec ManifestSpec) string {
	pip := "[]"
	if len(spec.PipPackages) > 0 {
		quoted := make([]string, 0, len(spec.PipPackages))
		for _, p := range spec.PipPackages {
			quoted = append(quoted, fmt.Sprintf("%q", p))
		}
		pip = "[" + strings.Join(quoted, ", ") + "]"
	}
	workspace := spec.WorkspaceDir
	if workspace == "" {
		workspace = "."
	}

	return fmt.Sprintf(`# Generated by gil — Modal sandbox manifest for %[1]s
# Image hint: %[2]s
import json
import subprocess

import modal

app = modal.App(%[1]q)
image = modal.Image.debian_slim().pip_install(%[3]s)


@app.function(
    image=image,
    mounts=[modal.Mount.from_local_dir(%[4]q, remote_path="/workspace")],
)
def exec_in_sandbox(cmd: str, args: str) -> dict:
    """Run cmd with json-encoded argv inside the Modal sandbox.

    Args:
        cmd:  binary name (e.g., "bash").
        args: JSON-encoded list of string arguments (e.g., '["-c","ls"]').
    """
    argv = json.loads(args) if args else []
    p = subprocess.run([cmd, *argv], capture_output=True, text=True, cwd="/workspace")
    return {"stdout": p.stdout, "stderr": p.stderr, "exit": p.returncode}


@app.local_entrypoint()
def main(cmd: str, args: str = "[]") -> None:
    result = exec_in_sandbox.remote(cmd, args)
    # Print a compact JSON line so the Go side can parse it from stdout.
    print(json.dumps(result))
`, spec.AppName, spec.Image, pip, workspace)
}

// WriteManifest renders + writes the manifest to disk. Returns the path.
func WriteManifest(sessionID string, spec ManifestSpec) (string, error) {
	path := ManifestPath(sessionID)
	body := RenderManifest(spec)
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("modal: write manifest %s: %w", path, err)
	}
	return path, nil
}
